/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DefensesIndexRouteImport } from './routes/defenses/index'
import { Route as BulkRunsIndexRouteImport } from './routes/bulk-runs/index'
import { Route as ScenariosScenarioIdRouteImport } from './routes/scenarios/$scenarioId'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as BulkRunsBulkRunIdRouteImport } from './routes/bulk-runs/$bulkRunId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DefensesIndexRoute = DefensesIndexRouteImport.update({
  id: '/defenses/',
  path: '/defenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRunsIndexRoute = BulkRunsIndexRouteImport.update({
  id: '/bulk-runs/',
  path: '/bulk-runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdRoute = ScenariosScenarioIdRouteImport.update({
  id: '/scenarios/$scenarioId',
  path: '/scenarios/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRunsBulkRunIdRoute = BulkRunsBulkRunIdRouteImport.update({
  id: '/bulk-runs/$bulkRunId',
  path: '/bulk-runs/$bulkRunId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk-runs/$bulkRunId': typeof BulkRunsBulkRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/bulk-runs/': typeof BulkRunsIndexRoute
  '/defenses/': typeof DefensesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk-runs/$bulkRunId': typeof BulkRunsBulkRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/bulk-runs': typeof BulkRunsIndexRoute
  '/defenses': typeof DefensesIndexRoute
  '/models': typeof ModelsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk-runs/$bulkRunId': typeof BulkRunsBulkRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/bulk-runs/': typeof BulkRunsIndexRoute
  '/defenses/': typeof DefensesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk-runs/$bulkRunId'
    | '/runs/$runId'
    | '/scenarios/$scenarioId'
    | '/bulk-runs/'
    | '/defenses/'
    | '/models/'
    | '/runs/'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk-runs/$bulkRunId'
    | '/runs/$runId'
    | '/scenarios/$scenarioId'
    | '/bulk-runs'
    | '/defenses'
    | '/models'
    | '/runs'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/bulk-runs/$bulkRunId'
    | '/runs/$runId'
    | '/scenarios/$scenarioId'
    | '/bulk-runs/'
    | '/defenses/'
    | '/models/'
    | '/runs/'
    | '/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRunsBulkRunIdRoute: typeof BulkRunsBulkRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ScenariosScenarioIdRoute: typeof ScenariosScenarioIdRoute
  BulkRunsIndexRoute: typeof BulkRunsIndexRoute
  DefensesIndexRoute: typeof DefensesIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defenses/': {
      id: '/defenses/'
      path: '/defenses'
      fullPath: '/defenses/'
      preLoaderRoute: typeof DefensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-runs/': {
      id: '/bulk-runs/'
      path: '/bulk-runs'
      fullPath: '/bulk-runs/'
      preLoaderRoute: typeof BulkRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId': {
      id: '/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ScenariosScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-runs/$bulkRunId': {
      id: '/bulk-runs/$bulkRunId'
      path: '/bulk-runs/$bulkRunId'
      fullPath: '/bulk-runs/$bulkRunId'
      preLoaderRoute: typeof BulkRunsBulkRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRunsBulkRunIdRoute: BulkRunsBulkRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ScenariosScenarioIdRoute: ScenariosScenarioIdRoute,
  BulkRunsIndexRoute: BulkRunsIndexRoute,
  DefensesIndexRoute: DefensesIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
